# Generated by Django 6.0.2 on 2026-02-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_demo',
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
